c975LEvents:
    roleNeeded:
        type: string
        required: true
        default: ROLE_ADMIN
        info: "User's role needed to enable access to data linked to EventsBundle: i.e. ROLE_ADMIN (default)"
    folderPictures:
        type: string
        required: true
        default: events
        info: "Path where the pictures will be stored. The full path ('web/images/[folderPictures]') has to be added to .gitignore if Git is used"
    sitemapBaseUrl:
        type: string
        required: true
        default: null
        info: "Base url for sitemap creation without leading slash: i.e. https://example.com"
    sitemapLanguages:
        type: array
        required: false
        default: null
        info: "Array of available languages of the website: ['en', 'fr', 'es']"
c975LCommon:
    tinymceApiKey:
        type: string
        required: false
        default: null
        info: "Your Tinymce Api key if you use the cloud version"
    tinymceLanguage:
        type: string
        required: false
        default: null
        info: "Your tinymce language if you use one, MUST BE placed in 'web/vendor/tinymce/[tinymceLanguage].js: i.e. fr_FR"
