services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\EventsBundle\Command\:
        resource: '../../Command/*'

    c975L\EventsBundle\Controller\:
        resource: '../../Controller/*'

    c975L\EventsBundle\Service\:
        resource: '../../Service/*'

    c975L\EventsBundle\Twig\:
        resource: '../../Twig/*'

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
